version: '3'
services:
  input:
    build:
      args:
        jar: geo-monitoring-input/target/*.jar
    restart: always
    ports:
      - 0.0.0.0:8080:8080
  output:
    build:
      args:
        jar: geo-monitoring-output/target/*.jar
    restart: always
    ports:
      - 0.0.0.0:8081:8080
  web:
    build:
      context: geo-monitoring-web
    restart: always
    environment:
      PORT: 8082
    ports:
      - 0.0.0.0:8082:8082
  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo:/data/db
volumes:
  mongo:
