version: '3'
services:
  input:
    build:
      args:
        jar: geo-monitoring-input/target/*.jar
    restart: always
    ports:
      - 0.0.0.0:8080:8080
  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD:-admin}
    ports:
      - 0.0.0.0:8081:8081
volumes:
  mongo:
